/**
 * @module home_service
 * @description Shared home command operations and formatting helpers.
 */

const home_cache = require('../../utils/home_cache');
const { list_homes } = require('../../utils/container_utils');
const { stringify_error } = require('../../utils/error_utils');

/**
 * Execute a home operation and update cache when needed.
 * @param {object} bot - mineflayer bot instance.
 * @param {'list'|'tp'|'set'|'remove'} command - Home subcommand.
 * @param {string} [name] - Home name.
 * @returns {Promise<{ success: boolean, result?: unknown, error?: string }>}
 */
async function execute_home_operation(bot, command, name) {
    if (command === 'list') {
        if (home_cache.needs_refresh()) {
            try {
                const homes = await list_homes(bot);
                home_cache.set_from_gui(homes);
            } catch (err) {
                return {
                    success: false,
                    error: `GUI 同步失败: ${stringify_error(err)}`,
                };
            }
        }
        return {
            success: true,
            result: home_cache.get_list(),
        };
    }

    if (command === 'tp') {
        if (!name) {
            return { success: false, error: '缺少 home 名称' };
        }
        bot.chat(`/home ${name}`);
        return { success: true, result: name };
    }

    if (command === 'set') {
        if (!name) {
            return { success: false, error: '缺少 home 名称' };
        }
        bot.chat(`/sethome ${name}`);
        home_cache.add_home(name);
        return { success: true, result: name };
    }

    if (command === 'remove') {
        if (!name) {
            return { success: false, error: '缺少 home 名称' };
        }
        bot.chat(`/removehome ${name}`);
        home_cache.remove_home(name);
        return { success: true, result: name };
    }

    return {
        success: false,
        error: `未知 home 子指令: ${command}`,
    };
}

/**
 * Normalize a home list returned by an operation.
 * @param {unknown} result - Operation result.
 * @returns {string[]|null} Normalized home names.
 */
function normalize_home_list(result) {
    if (!Array.isArray(result)) {
        return null;
    }

    const names = [];
    for (const entry of result) {
        if (typeof entry === 'string') {
            const name = entry.trim();
            if (name) {
                names.push(name);
            }
            continue;
        }

        if (entry && typeof entry === 'object') {
            const candidate = [entry.name, entry.label, entry.home, entry.title]
                .find((item) => typeof item === 'string' && item.trim());
            if (candidate) {
                names.push(candidate.trim());
            }
        }
    }

    return [...new Set(names)];
}

/**
 * Format a home operation response.
 * @param {string} command - Home subcommand.
 * @param {boolean} success - Whether operation succeeded.
 * @param {unknown} result - Operation result.
 * @param {unknown} error - Operation error.
 * @param {string} [name] - Home name.
 * @returns {string} Response text.
 */
function format_home_result_message(command, success, result, error, name) {
    const error_message = stringify_error(error);

    if (command === 'list') {
        if (!success) {
            return `获取 home 列表失败: ${error_message}`;
        }
        const homes = normalize_home_list(result);
        if (homes && homes.length > 0) {
            return `Home 列表: ${homes.join(', ')}`;
        }
        if (typeof result === 'string' && result.trim()) {
            return `Home 列表: ${result.trim()}`;
        }
        return '没有设置任何 home';
    }

    if (command === 'tp') {
        return success
            ? `已传送到 home: ${name || result || ''}`.trim()
            : `传送失败: ${error_message}`;
    }

    if (command === 'set') {
        return success
            ? `已设置 home: ${name || result || ''}`.trim()
            : `设置失败: ${error_message}`;
    }

    if (command === 'remove') {
        return success
            ? `已删除 home: ${name || result || ''}`.trim()
            : `删除失败: ${error_message}`;
    }

    return success ? String(result || '') : `操作失败: ${error_message}`;
}

/**
 * Check whether a message is generated by the home GUI sync.
 * @param {object} msg - msg_obj.
 * @returns {boolean} Whether it should be suppressed from forwarding.
 */
function is_home_related_message(msg) {
    const text = String((msg && msg.message) || '').trim();
    if (!text) {
        return false;
    }

    return text.includes('点击传送至')
        || text.includes('Shift+右键来移除家')
        || text.includes('按 Q 编辑')
        || /^#\d+:\s*x\d+/i.test(text);
}

module.exports = {
    execute_home_operation,
    normalize_home_list,
    format_home_result_message,
    is_home_related_message,
};
